# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecarddb', '0003_reasonsnosale_referralsources'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
        migrations.RenameModel(
            old_name='ReasonsNoSale',
            new_name='ReasonNoSale',
        ),
        migrations.RenameModel(
            old_name='ReferralSources',
            new_name='ReferralSource',
        ),
    ]
