# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorecarddb', '0005_scorecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='open_state_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='open_state_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='patient_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scorecarddb.ReasonNoSale'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='referral',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scorecarddb.ReferralSource'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='sale_made',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='y', max_length=1),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='third_party',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='y', max_length=1),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
