# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecarddb', '0007_auto_20171104_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='open_state_score',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
