# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecarddb', '0009_auto_20171105_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorecard',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='open_state_score',
            field=models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=0, max_length=1),
        ),
    ]
