# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecarddb', '0011_auto_20171105_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='reviewer',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
