# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecarddb', '0014_auto_20171105_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralsource',
            name='referral_source',
            field=models.CharField(max_length=30),
        ),
    ]
