# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecarddb', '0017_auto_20171105_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location_state', 'location_city']},
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='date',
        ),
    ]
