# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecarddb', '0018_auto_20171111_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorecard',
            name='time',
        ),
    ]
