# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecarddb', '0019_remove_scorecard_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
