# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecarddb', '0022_auto_20171111_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='total_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
