# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorecarddb', '0023_scorecard_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scorecarddb.ReasonNoSale'),
        ),
    ]
