# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorecarddb', '0026_auto_20171111_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='referral',
            field=models.ForeignKey(help_text='tester text!', null=True, on_delete=django.db.models.deletion.SET_NULL, to='scorecarddb.ReferralSource', verbose_name='Referral source'),
        ),
    ]
