# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorecarddb', '0027_auto_20171111_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='open_state_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, verbose_name='Opening Statement'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='referral',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scorecarddb.ReferralSource', verbose_name='Referral source'),
        ),
    ]
