# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecarddb', '0028_auto_20171111_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='anatomy_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, verbose_name='Anatomy of the Ear'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='causes_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, verbose_name='Discuss Possible Causes for Loss'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='clinical_study_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, verbose_name='Referenced a Clinical Study'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='commitment_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, verbose_name='Commitment'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='last_test_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, verbose_name='Last Hearing Test'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='pain_points_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, verbose_name='Discovery of Pain Points'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='progressive_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, verbose_name='Described hearing loss as Progressive, Permanent, and Irreversible'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='sum_val_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, verbose_name='Gives a Summary Validation of COSI Goals'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='verb_COSI_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, verbose_name='Verbalizes Pain Points as COSI Goals'),
        ),
    ]
