# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorecarddb', '0031_auto_20171111_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='COSI_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='Implements PT COSI goals during the anatomy, FVT, audiogram, prescription & recommendation', verbose_name='Use of COSI'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='FVT_exp_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='3) Expect 100% correct, missing 1-2 is a red flag, any more will be a cause for concern', verbose_name='Expectations'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='FVT_results_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='3) Refers back to expectations, reviews response examples, realization of PT loss is impactful', verbose_name='Results'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='FVT_third_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='1) Asks a single direct question, 2) Asks multiple follow-up questions 3) draws out emotion, gets perspective', verbose_name='Discussed results with the third party'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='anatomy_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='1) Verbal description 2) Uses diagram 3) Specific reference to otoscope AND audiogram', verbose_name='Anatomy of the Ear'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='appropriate_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='Explains that a lower level of technology is NOT an inferior HA', verbose_name='State that all recommendations are appropriate'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='authority_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='Utilizes strong parent/child relationship to maintain control and direction', verbose_name='Authority'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='bad_good_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='1) Separates Bad News/Good News, 2) Insert COSI, 3) Discuss Proper Amplification', verbose_name='Bad News/Good News'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='body_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='Ex: Sits up straight, leans forward when appropriate to show engagement', verbose_name='Body Language'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='causes_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='3) Age, Noise Exposure, Medical History, Genetics', verbose_name='Discuss Possible Causes for Loss'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='clinical_study_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='Names an institutional study', verbose_name='Referenced a Clinical Study'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='commitment_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='1) Asks a commitment question 2) Addresses objections 3) Recommits', verbose_name='Commitment'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='cred_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='Establishes themselves as a medical professional', verbose_name='Credibility'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='explain_audio_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='1) Explains volume and frequency axis, 3) explains speech recognition test', verbose_name='Explained audiogram'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='fight_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='References COSI and Auditory Deprivation', verbose_name='Fight for the sale?'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='impact_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='Helps PT internalize their loss and realize its severity (personal story, FVT, bad news/good news)', verbose_name='Impact'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='involvement_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='Follows 70/30 Rule, PT opens up with hearing struggle, seeks acknowledgement throughout recommendation', verbose_name='Patient Involvement'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='last_test_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='1) Finds out date 2) What were the results? 3) Recommends an annual exam', verbose_name='Last Hearing Test'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='maintain_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='3) Explains speech understanding and how HA maintain it, uses an analogy', verbose_name='Discussed need to maintain what is left'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='normal_hearing_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='1) Explains normal hearing 2) Explains HL is any hearing below 20db 3) Specifies anything below 20db will require corrective treatment', verbose_name='Normal hearing vs. hearing loss'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='notions_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='"What have you heard good or not so good about HA?"', verbose_name='Discover if patient has preconceived notions of hearing aids'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='objections_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='1) Acknowledges concern 2) Addresses concerns 3) Moves forward without creating more objections', verbose_name='How well did they overcome objections?'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='otoscope_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='1) Uses otoscope 3) Sets proper expectations prior and gives thorough explanation after', verbose_name='Otoscope'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='pain_points_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='1) Asks 2) Identifies multiple lifestyle pain points 3) Discovers related emotional markers', verbose_name='Discovery of Pain Points'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='pick_two_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='3) Presents choices, has PT pick, references BOTH choices during the P&R', verbose_name='5 most important things'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='progressive_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='3) States/defines all three words and creates urgency by explaining how each relates to HL', verbose_name='Described hearing loss as Progressive, Permanent, and Irreversible'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='questions_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='Asks more open than closed ended questions, properly digs for details', verbose_name='Open Ended Questions'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='rapport_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='PT trusts practitioner, practitioner shows interest and concern', verbose_name='Rapport'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scorecarddb.ReasonNoSale'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='recommit_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='References 1st commitment and/or FVT results, confirms willingness, seeks acknowledgement', verbose_name='Recommitment'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='restate_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='Consistently restates PT pain points so they feel heard/understood', verbose_name='Restate'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='sep_rec_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='Settles on a specific style before moving on to technology, does not bounce back and forth', verbose_name='Separate style and technology completely'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='story_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='3) Practitioner relates an emotionally impactful personal story that describes the effects of untreated HL', verbose_name='Personal story'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='style_cost_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='1) Says that style has no bearing on cost 3) Explains that style is based on looks and comfort', verbose_name='States style has no bearing on cost'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='style_fitting_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='Uses style guide to show WHY certain styles are appropriate, narrows down to 2-3, thoroughly explains differences between remaining styles', verbose_name='Used Audiogram Style Fitting Guide'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='tech_fitting_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='Uses tech fitting guide, based on lifestyle and budget', verbose_name='Used Technology Fitting Guide (Triangle or similar)'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='tech_levels_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text="Inserts specific COSI goals to explain the levels of technology and helps PT visualize where they fall on the triangle (don't just list off COSI)", verbose_name='Explanation of Technology Levels w/COSI references'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='third_party_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='Involves 3rd party at every level of the DE', verbose_name='3rd Party Interaction'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='tone_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='Tone demonstrates concern and consideration especially during the FVT results and bad news/good news', verbose_name='Tone'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='transitions_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='Smoothly moves from one DE section to the next, all necessary items take place before or after the audiogram', verbose_name='Transitions'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='urgency_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='Throughout the entire DE, PT understands how HL is a "ticking clock," and that they are much worse off leaving their HL untreated', verbose_name='Urgency'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='validation_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='Validates each specific pain point, thorough summary validation, validates each objection', verbose_name='Validation'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='verb_COSI_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='Explicitly explains that the pain points will be used as verifiable goals', verbose_name='Verbalizes Pain Points as COSI Goals'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='words_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='Conveys confidence through clarity and conciseness with ALL explanations, no weak verbiage (maybe, I think, a little), does not mispronounce clinical terms', verbose_name='Words'),
        ),
    ]
