# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecarddb', '0033_auto_20171119_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='appropriate_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (2, 2)], default=0, help_text='Explains that a lower level of technology is NOT an inferior HA', verbose_name='State that all recommendations are appropriate'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='ask_chart_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (2, 2)], default=0, verbose_name='Asked where patient expected to be on the chart'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='backup_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (2, 2)], default=0, verbose_name='Get backup hearing aid'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='clinical_study_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (2, 2)], default=0, help_text='Names an institutional study', verbose_name='Referenced a Clinical Study'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='notions_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (2, 2)], default=0, help_text='"What have you heard good or not so good about HA?"', verbose_name='Discover if patient has preconceived notions of hearing aids'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='sep_rec_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (2, 2)], default=0, help_text='Settles on a specific style before moving on to technology, does not bounce back and forth', verbose_name='Separate style and technology completely'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='sum_val_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (2, 2)], default=0, verbose_name='Gives a Summary Validation of COSI Goals'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='verb_COSI_score',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (2, 2)], default=0, help_text='Explicitly explains that the pain points will be used as verifiable goals', verbose_name='Verbalizes Pain Points as COSI Goals'),
        ),
    ]
