# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecarddb', '0034_auto_20171125_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='employment_status',
            field=models.CharField(choices=[('Trainee', 'Trainee'), ('Current', 'Current'), ('Terminated', 'Terminated')], max_length=10, null=True),
        ),
    ]
