# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-09 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecarddb', '0035_practitioner_employment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='audio_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='ce_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='comm_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='emo_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='fvt_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='intro_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='pr_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='pro_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
