# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-16 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecarddb', '0036_auto_20180309_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practitioner',
            options={'ordering': ['practitioner_last_name', 'practitioner_first_name']},
        ),
    ]
